default:
  image: ruby:2.7
  before_script:
    - apt -y install nodejs yarnpkg
    - bundle install

pages:
  stage: deploy
  script:
    - bundle exec middleman build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
