[build]
base = "./"
command = "bundle exec middleman build --verbose"
publish = "build"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
from = "/"
to = "/results/"
status = 302

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1FwPwN9vFKjEnJxHYJG6hzOMnMSCKzCpPGE-n_KSHyGs/copy"
