[build]
base = "./"
command = "bundle exec middleman build"
publish = "./build"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
from = "https://unosmium.netlify.com/*"
to = "https://unosmium.org/:splat"
status = 301
force = true

[[redirects]]
from = "/"
to = "/results/"
status = 302
