# This is a basic workflow to help you get started with Actions

name: Netlify deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Check identity and push
        env:
          JASON_MD5: ${{ secrets.JASON_MD5 }}
          NETLIFY_DEPLLOY_URL: ${{ secrets.NETLIFY_DEPLOY_URL }}
        run: |
          cd $GITHUB_WORKSPACE
          if [[ $(git log --name-status HEAD^..HEAD | grep Author | cut -d'<' -f 2- | cut -d'>' -f -1 | md5sum | cut -d' ' -f -1) == $JASON_MD5 ]]; then; curl -X POST $NETLIFY_DEPLOY_URL; fi
